name: test_unsupported_step_with
on: push
jobs:
  test_unsupported_step_with:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
        - with:
            script: |
              console.log("Hello World")
    steps:
    - name: Test
      uses: actions/github-script@v7
      with: ${{ matrix.with }}
