name: test_unsupported_env_syntax
on: push
jobs:
  test_unsupported_env_syntax:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          env:
            KEY: VAL
    env: ${{ matrix.env }}
    steps:
    - name: Test
      run: exit 0