name: test_unsupported_job_env
on: push
jobs:
  test_unsupported_job_env:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
        - env:
            KEY: VAL
    env: ${{ matrix.env }}
    steps:
    - name: Test
      run: exit 0