name: container-matrix
on: push
jobs:
  container-matrix-test:
    strategy:
      matrix:
        test: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
    runs-on: [self-hosted]
    container: ubuntu:latest
    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          console.log('Hello from NodeJS Actions in a container!');
    - run: echo Hello World
