name: format-substitution
on: push
jobs:
  format-substitution-test:
    strategy:
      matrix:
        test1: [ false ]
        test2: [ true ]
        test3: [ 0 ]
        test4: [ 99 ]
        test5: [ 'Hello World' ]
    runs-on: [self-hosted]
    steps:
    - run: |
        echo ${{matrix.test1}}-${{matrix.test2}}-${{matrix.test3}}-${{matrix.test4}}-${{matrix.test5}}${{matrix.test6}}
        echo ${{github.actor}}
        echo ${{github.event_name}}
        test="Hello World"
        echo $test
        echo ${test}
