name: matrix
on: push
jobs:
  matrix-test:
    strategy:
      matrix:
        test: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
    runs-on: [self-hosted]
    steps:
    - run: echo Hello World